name: Rust Multi-Platform Release (ARM + Windows GNU)

on:
  push:
    tags:
      - "v*"

env:
  CARGO_TERM_COLOR: always
  BIN_NAME: vda_server

jobs:
  build:
    permissions:
      contents: write
    name: Build (${{ matrix.target }})
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        include:
          # Linux GNU x64
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu

          # Linux MUSL x64 (Synology Intel)
          - os: ubuntu-latest
            target: x86_64-unknown-linux-musl

          # Windows MSVC x64
          - os: windows-latest
            target: x86_64-pc-windows-msvc

          # Windows GNU x64
          - os: windows-latest
            target: x86_64-pc-windows-gnu

          # Windows MSVC x86
          - os: windows-latest
            target: i686-pc-windows-msvc

          # Windows MSVC ARM64
          - os: windows-latest
            target: aarch64-pc-windows-msvc

          # macOS Intel
          - os: macos-latest
            target: x86_64-apple-darwin

    steps:
      - uses: actions/checkout@v4

      - name: Package plugin
        run: |
          cd plugin
          zip -r ../plugin.zip .
          echo "PLUGIN_OUT=plugin.zip" >> $GITHUB_ENV

      - name: Upload plugin to Release
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ env.PLUGIN_OUT }}

      - name: Install Rust target
        run: rustup target add ${{ matrix.target }}

      # MUSL + cross tools (x86_64 + aarch64)
      - name: Install MUSL tools
        if: startsWith(matrix.target, 'x86_64-unknown-linux-musl')
        run: |
          sudo apt update
          sudo apt install -y musl-tools

      - name: Install ARM64 MUSL tools
        if: matrix.target == 'aarch64-unknown-linux-musl'
        run: |
          sudo apt update
          sudo apt install -y gcc-aarch64-linux-gnu

      # Cache Cargo
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-${{ matrix.target }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Build release
        run: cargo build --release --target ${{ matrix.target }} 

      - name: Rename binary
        shell: bash
        run: |
          EXT=""
          if [[ "${{ matrix.os }}" == "windows-latest" ]]; then
            EXT=".exe"
          fi

          SRC="target/${{ matrix.target }}/release/${BIN_NAME}${EXT}"
          DST="${BIN_NAME}-${{ matrix.target }}${EXT}"

          cp "$SRC" "$DST"
          echo "BIN_OUT=$DST" >> $GITHUB_ENV

      - name: Upload binary to Release
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ env.BIN_OUT }}

      - name: Build SPK package
        if: matrix.target == 'x86_64-unknown-linux-musl'
        run: |
          mkdir -p relese/_temp _build/Spk _build/package
          packageName=$(grep '^package=' "SPK_AP_TEMPLATE/INFO" | cut -d'=' -f2 | sed 's/"//g' | tr -d ' ')
          cp ${{ env.BIN_OUT }} SPK_AP_TEMPLATE/pakiet/
          rsync -av --exclude='pakiet' SPK_AP_TEMPLATE/ _build/Spk/
          rsync -ah SPK_AP_TEMPLATE/pakiet/ _build/package/
          cd _build/package
          tar czf ../Spk/package.tgz *
          cd ../Spk
          tar cf ../../relese/_temp/${packageName}.spk *
          cd ../..
          echo "SPK_OUT=relese/_temp/${packageName}.spk" >> $GITHUB_ENV

      - name: Upload SPK to Release
        if: matrix.target == 'x86_64-unknown-linux-musl'
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ env.SPK_OUT }}
